export const TOOL_OPTIONS: string[] = [
  'GoHighLevel',
  'Slack',
  'n8n',
  'Zapier / Make',
  'Google Workspace',
  'Monday / Asana',
  'Notion',
  'Stripe / Whop',
  'ChatGPT',
  'Claude',
  'Airtable',
  'ClickUp',
  'Custom / Other',
]
